[asyncio]
debug = false
slow_callback_duration = 10.0

[loguru.logger]
remove = true

[[loguru.logger.add]]
sink = "DEBUG.log"
level = "DEBUG"
format = "# {level.name}[{level.no}] | {time:YYYY-MM-DD HH:mm:ss.SSS Z} | {process.name}[{process.id}]:{thread.name}[{thread.id}] | File \"{file.path}\", line {line}, in {function}\n{message}\n"
enqueue = false
rotation = "8 MB"
retention = 2

[[loguru.logger.add]]
sink = "INFO.log"
level = "INFO"
format = "# {level.name}[{level.no}] | {time:YYYY-MM-DD HH:mm:ss.SSS Z} | {process.name}[{process.id}]:{thread.name}[{thread.id}] | File \"{file.path}\", line {line}, in {function}\n{message}\n"
enqueue = false
rotation = "8 MB"
retention = 128

[[loguru.logger.add]]
sink = "SUCCESS.log"
level = "SUCCESS"
format = "# {level.name}[{level.no}] | {time:YYYY-MM-DD HH:mm:ss.SSS Z} | {process.name}[{process.id}]:{thread.name}[{thread.id}] | File \"{file.path}\", line {line}, in {function}\n{message}\n"
enqueue = false
rotation = "8 MB"
retention = 128

[[loguru.logger.add]]
sink = "WARNING.log"
level = "WARNING"
format = "# {level.name}[{level.no}] | {time:YYYY-MM-DD HH:mm:ss.SSS Z} | {process.name}[{process.id}]:{thread.name}[{thread.id}] | File \"{file.path}\", line {line}, in {function}\n{message}\n"
enqueue = false
rotation = "8 MB"
retention = 128

[[loguru.logger.add]]
sink = "ERROR.log"
level = "ERROR"
format = "# {level.name}[{level.no}] | {time:YYYY-MM-DD HH:mm:ss.SSS Z} | {process.name}[{process.id}]:{thread.name}[{thread.id}] | File \"{file.path}\", line {line}, in {function}\n{message}\n"
enqueue = false
rotation = "8 MB"
retention = 128

[[loguru.logger.add]]
sink = "CRITICAL.log"
level = "CRITICAL"
format = "# {level.name}[{level.no}] | {time:YYYY-MM-DD HH:mm:ss.SSS Z} | {process.name}[{process.id}]:{thread.name}[{thread.id}] | File \"{file.path}\", line {line}, in {function}\n{message}\n"
enqueue = false
rotation = "8 MB"
retention = 128

[[monitors]]
cls = "PositionMonitor"
minute = 2
drawdown_percent_threshold = 5.0

[[monitors]]
cls = "MarketMonitor"
params = { "1m" = 10.0, "5m" = 15.0, "1h" = 25.0, "4h" = 40.0 }
speed = 3
maxm = 256

[[monitors]]
cls = "OrderMonitor"

[[monitors]]
cls = "ExchangeMonitor"
minute = 4
