[project]
name = "binance-futures-monitor"
version = "0.1.0"
description = "Binance Futures Monitor"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiofiles==24.1.0",
    "aiohttp==3.12.14",
    "binance-futures-connector==4.1.0",
    "loguru==0.7.3",
    "pandas>=2.3.2",
]
